app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => ['web']], function () {

    Route::get('/', function () {
        return redirect()->action('RankingController@overall');
    });

    // Auth
    Route::group(['namespace' => 'Auth'], function(){
        Route::get('login', [
            'as'   => 'auth.login',
            'uses' =>  'AuthController@getLogin'
        ]);
        
        Route::post('login',[
            'as'   => 'auth.login',
            'uses' =>  'AuthController@postLogin'
        ]);

        Route::get('logout', [
            'as'   => 'auth.logout',
            'uses' =>  'AuthController@logout'
        ]);
    });

    // Ranking
    Route::get('ranking/overall', [
        'as' => 'ranking.overall',
        'uses' => 'RankingController@overall'
    ]);
    Route::get('ranking/overall/vice-president', [
        'as' => 'ranking.overall-vice-president',
        'uses' => 'RankingController@overallVicePresident'
    ]);
    Route::get('ranking/regional', [
        'as' => 'ranking.regional',
        'uses' => 'RankingController@regional'
    ]);
    Route::get('ranking/regional/vice-president', [
        'as' => 'ranking.regional-vice-president',
        'uses' => 'RankingController@regionalVicePresident'
    ]);
    Route::get('ranking/provincial', [
        'as' => 'ranking.provincial',
        'uses' => 'RankingController@provincial'
    ]);
    Route::get('ranking/provincial/vice-president', [
        'as' => 'ranking.provincial-vice-president',
        'uses' => 'RankingController@provincialVicePresident'
    ]);
    Route::get('ranking/coc/president', [
        'as' => 'ranking.coc-president',
        'uses' => 'RankingController@cocPresident'
    ]);
    Route::get('ranking/coc/vice-president', [
        'as' => 'ranking.coc-vice-president',
        'uses' => 'RankingController@cocVicePresident'
    ]);

    // Maps
    Route::get('ranking/map/count-received-president', [
        'as' => 'ranking.count-received-president',
        'uses' => 'RankingController@countReceivedPresident'
    ]);
    Route::get('ranking/map/count-received-vice-president', [
        'as' => 'ranking.count-received-vice-president',
        'uses' => 'RankingController@countReceivedVicePresident'
    ]);
    Route::get('ranking/map/per-area-president', [
        'as' => 'ranking.per-area-president',
        'uses' => 'RankingController@perAreaPresident'
    ]);
    Route::get('ranking/map/per-area-vice-president', [
        'as' => 'ranking.per-area-vice-president',
        'uses' => 'RankingController@perAreaVicePresident'
    ]);
    

    // Reports
    Route::get('report/voters-turnout/regional', [
        'as' => 'report.voters-turnout-regional',
        'uses' => 'ReportController@votersTurnoutRegional'
    ]);
    Route::get('report/voters-turnout/provincial', [
        'as' => 'report.voters-turnout-provincial',
        'uses' => 'ReportController@votersTurnoutProvincial'
    ]);
    Route::get('report/discrepancies-president', [
        'as' => 'report.discrepancies-president',
        'uses' => 'ReportController@discrepanciesPresident'
    ]);
    Route::get('report/discrepancies-vice-president', [
        'as' => 'report.discrepancies-vice-president',
        'uses' => 'ReportController@discrepanciesVicePresident'
    ]);
    Route::get('report/registered-vs-actual-president', [
        'as' => 'report.registered-vs-actual-president',
        'uses' => 'ReportController@registeredVsActualPresident'
    ]);
    Route::get('report/registered-vs-actual-vice-president', [
        'as' => 'report.registered-vs-actual-vice-president',
        'uses' => 'ReportController@registeredVsActualVicePresident'
    ]);
    Route::get('report/registered-vs-coc-president', [
        'as' => 'report.registered-vs-coc-president',
        'uses' => 'ReportController@registeredVsCocPresident'
    ]);
    Route::get('report/registered-vs-coc-vice-president', [
        'as' => 'report.registered-vs-coc-vice-president',
        'uses' => 'ReportController@registeredVsCocVicePresident'
    ]);

    // Input
    // Admin
    Route::group(['prefix' => 'input'], function(){
        Route::get('import', [
            'as' => 'import',
            'uses' => 'ImportController@import'
        ]);

        // Manual Quick Count
        Route::get('manual', [
            'as' => 'manual',
            'uses' => 'OfficialCountController@presidentIndex'
        ]);
        Route::get('manual/{candidate_id}/{province_id}/edit', [
            'as' => 'manual.edit',
            'uses' => 'OfficialCountController@editCount'
        ]);
        Route::post('manual/{candidate_id}/{province_id}/update', [
            'as' => 'manual.update',
            'uses' => 'OfficialCountController@updateCount'
        ]);
        Route::get('manual/vice-president', [
            'as' => 'manual.vice-president',
            'uses' => 'OfficialCountController@vicePresidentIndex'
        ]);
        Route::get('manual/vice-president/{candidate_id}/{province_id}/edit', [
            'as' => 'manual.vice-president.edit',
            'uses' => 'OfficialCountController@editVicePresidentCount'
        ]);
        Route::post('manual/vice-president/{candidate_id}/{province_id}/update', [
            'as' => 'manual.vice-president.update',
            'uses' => 'OfficialCountController@updateVicePresidentCount'
        ]);
        // Monitoring
        Route::get('monitoring', [
            'as' => 'manual.monitoring',
            'uses' => 'MonitoringController@index'
        ]);
        Route::get('monitoring/{province_id}/edit', [
            'as' => 'manual.monitoring.edit',
            'uses' => 'MonitoringController@edit'
        ]);
        Route::post('monitoring/{province_id}/update', [
            'as' => 'manual.monitoring.update',
            'uses' => 'MonitoringController@update'
        ]);

        // PPCRV COC
        Route::get('ppcrv-coc', [
            'as' => 'ppcrv-coc',
            'uses' => 'PpcrvCountController@index'
        ]);
        Route::get('ppcrv-coc/{province_id}/edit', [
            'as' => 'ppcrv-coc.edit',
            'uses' => 'PpcrvCountController@edit'
        ]);
        Route::post('ppcrv-coc/{province_id}/update', [
            'as' => 'ppcrv-coc.update',
            'uses' => 'PpcrvCountController@update'
        ]);
    });

    // Admin
    Route::group(['prefix' => 'admin'], function(){
        Route::resource('candidate', 'CandidateController');
        // User
        Route::get('user/{id}/change-password', [
            'as' => 'admin.user.change-password',
            'uses' =>  'UserController@changePassword'
        ]);
        Route::post('user/{id}/updatePassword', [
            'as' => 'admin.user.update-password',
            'uses' => 'UserController@updatePassword'
        ]);
        Route::resource('user', 'UserController');

        // Configuration
        Route::get('config/reset-database', [
            'as' => 'config.reset-database',
            'uses' => 'ConfigController@resetDatabase'
        ]);
        Route::post('config/save-reset-database', [
            'as' => 'config.save-reset-database',
            'uses' => 'ConfigController@saveResetDatabase'
        ]);
    });
    

});

app/Candidate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use DB;

class Candidate extends Model
{
    use SoftDeletes;

    protected $fillable = ['first_name', 'last_name', 'middle_name', 'display_name',
    	'code', 'position', 'photo', 'remarks', 'color', 'last_updated_by'];

    protected $dates = ['deleted_at'];

    public function getOverallQuickCount()
    {
        $count = 0;
        $provinces = Province::all();

        foreach($provinces as $province) {
            $quickCount = OfficialCount::where('candidate_id', $this->id)
                ->where('province_id', $province->id)
                ->orderBy('id', 'desc')
                ->first();

            if($quickCount) $count += $quickCount;
        }
       
        return $count;
    }

    public function getNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }
}

app/Http/Controllers/CandidateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\CandidateRepository;
use App\Http\Requests;
use App\Http\Requests\CandidateRequest;
use Gate;

class CandidateController extends Controller
{
    protected $candidate;

    function __construct(CandidateRepository $candidate)
    {
        ini_set('xdebug.max_nesting_level', 200);

        $this->candidate = $candidate;

        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Gate::denies('manage-candidates')) {
            return redirect('/');
        }

        $candidates = $this->candidate->getAll();

        return view('candidate.index')
            ->with('candidates', $candidates)
            ->with('page_title', 'List of Candidates');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Gate::denies('manage-candidates')) {
            return redirect('/');
        }

        $positions = $this->getPositions();

        return view('candidate.create')
            ->with('candidate', null)
            ->with('positions', $positions)
            ->with('page_title', 'Create Candidate');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CandidateRequest $request)
    {
        if(Gate::denies('manage-candidates')) {
            return redirect('/');
        }

        $candidate = $this->candidate->create($request->all());

        $request->session()->flash('success_message', 'Successfully added candidate, <strong>'.$candidate->last_name.'</strong>.');

        return redirect()->route('admin.candidate.index', $candidate->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Gate::denies('manage-candidates')) {
            return redirect('/');
        }

        $candidate = $this->candidate->get($id);
        $positions = $this->getPositions();

        return view('candidate/edit')
            ->with('candidate', $candidate)
            ->with('positions', $positions)
            ->with('page_title', 'Edit Candidate');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CandidateRequest $request, $id)
    {
        if(Gate::denies('manage-candidates')) {
            return redirect('/');
        }

        $candidate = $this->candidate->update($id, $request->all());

        $request->session()->flash('success_message', 'Successfully updated candidate, <strong>'.$candidate->last_name.'</strong>.');

        return redirect()->route('admin.candidate.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if(Gate::denies('manage-candidates')) {
            return redirect('/');
        }

        $candidate = $this->candidate->destroy($id);
        
        $request->session()->flash('success_message', 'Successfully deleted candidate, <strong>'.$candidate->last_name.'</strong>.');
        
        return redirect()->route('admin.candidate.index');
    }

    private function getPositions()
    {
        if(Gate::denies('manage-candidates')) {
            return redirect('/');
        }
        
        return array('president' => 'President',
            'vice_president' => 'Vice President',
            'senator' => 'Senator');
    }
}

resources/views/candidate/create.blade.php
@extends('admin_template')

@section('head')
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
@endsection

@section('content')
	{!! Form::model($candidate, ['method' => 'POST', 'route' => ['admin.candidate.store'], 'files' => true]) !!}
	    @include('candidate.form', ['mode' => 'create'])
		<div class="row">
		    <div class="col-xs-12">
		    	<div class="pull-left">
	    			<button type="submit" class="btn btn-primary btn-flat">Create Candidate</button>
		            <a href="{{ route('admin.candidate.index') }}" class="btn"><u>Cancel</u></a>
		    	</div>
		    </div>
		</div>
	{!! Form::close() !!}	    
@endsection

@section('script')
	<script src="{{ asset("admin_theme/plugins/jQueryUI/jquery-ui.min.js") }}" type="text/javascript"></script>

	<script>
	  $(function() {
	    $( "#birthdate" ).datepicker({
	      changeMonth: true,
	      changeYear: true,
	      dateFormat: 'yy-mm-dd'
	    });
	  });
	</script>
@endsection

resources/views/candidate/edit.blade.php
@extends('admin_template')

@section('content')
	{!! Form::model($candidate, ['method' => 'PUT', 'route' => ['admin.candidate.update', $candidate->id], 'files' => true]) !!}
	    @include('candidate.form', ['mode' => 'edit'])
	    {!! Form::submit('', ['id' => 'submit-form', 'class' => 'hidden']) !!}
	{!! Form::close() !!}
		<div class="row">
		    <div class="col-xs-12">
		    	<div class="pull-left">
		    		<label for="submit-form" class="btn btn-primary btn-flat">Update Candidate</label>
		            <a href="{{ route('admin.candidate.index') }}" class="btn"><u>Cancel</u></a>
		    	</div>
		    	<div class="pull-right">
		    		{!! Form::open(['method' => 'DELETE', 'route' => ['admin.candidate.destroy', $candidate->id]]) !!}
						@if(is_null($candidate->deleted_at))
							<button type="submit" class="btn btn-danger btn-sm btn-flat" onclick="return confirm('Are you sure you want to delete candidate?')"><strong>Delete Candidate</strong></button>
						@endif
					{!! Form::close() !!}
		    	</div>
		    </div>
		</div>
	{!! Form::close() !!}
@endsection

resources/views/candidate/form.blade.php
<div class="row">
  <div class="col-xs-12">
    <div class="box">
    	<div class="box-header with-border">
        <!-- <h3 class="box-title">Enroller Profile</h3> -->
      </div><!-- /.box-header -->
      <div class="box-body">
        <div class="form-group  {{ $errors->has('photo') ? 'has-error' : '' }}">
          <label>Photo</label>
          <br>
          @if($mode === 'edit')
            @if(isset($candidate) && $candidate->photo)
              <img src="{{ url($candidate->photo) }}" alt="User Image" height="100px" />
            @else
              <img src="{{ asset('images/default-user.png') }}" alt="User Image" />
            @endif
          @endif
          <input type="file" name="photo">
        </div>
        <div class="form-group  {{ $errors->has('first_name') ? 'has-error' : '' }}">
          <label>First Name</label>
          {!! Form::text('first_name', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group  {{ $errors->has('last_name') ? 'has-error' : '' }}">
          <label>Last Name</label>
          {!! Form::text('last_name', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group  {{ $errors->has('middle_name') ? 'has-error' : '' }}">
          <label>Middle Name</label>
          {!! Form::text('middle_name', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group  {{ $errors->has('position') ? 'has-error' : '' }}">
          <label>Position</label>
          {!! Form::select('position', $positions, null, ['placeholder' => '- Select Position -', 'class' => 'form-control', 'style' => 'width:100%']) !!}
        </div>
        <div class="form-group  {{ $errors->has('code') ? 'has-error' : '' }}">
          <label>Code</label>
          {!! Form::text('code', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group  {{ $errors->has('color') ? 'has-error' : '' }}">
          <label>Color</label>
          {!! Form::text('color', null, ['class' => 'form-control']) !!}
        </div>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div><!-- /.col -->
</div><!-- /.row -->

resources/views/candidate/index.blade.php
@extends('admin_template')

@section('head')
	<!-- DATA TABLES -->
    <link href="{{ asset('admin_theme/plugins/datatables/dataTables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')
<div class="row">
	<div class="col-xs-12">
		<a href="{{ route('admin.candidate.create') }}" class="btn btn-primary btn-flat fa fa-plus"> Add New</a>
		<br/><br/>

		<div class="box">
	      	<div class="box-header">
	      		<!-- <h3 class="box-title">President</h3> -->
	      	</div><!-- /.box-header -->
	      	<div class="box-body">
		      	<table id="data_table" class="table table-bordered table-striped">
		      		<thead>
		      			<tr>
		      				<th>First Name</th>
		      				<th>Last Name</th>
		      				<th>Middle Name</th>
		      				<th>Code</th>
		      				<th>Position</th>
		      				<th></th>
		      			</tr>
		      		</thead>
		      		<tbody>
		      			@foreach($candidates as $candidate)
			      			<tr>
			      				<td>{{ $candidate->first_name }}</td>
			      				<td>{{ $candidate->last_name }}</td>
			      				<td>{{ $candidate->middle_name }}</td>
			      				<td>{{ $candidate->code }}</td>
			      				<td>{{ $candidate->position }}</td>
			      				<td align="center"><a href="{{ route('admin.candidate.edit', $candidate->id) }}"><i class="fa fa-pencil"></i></a></td>
			      			</tr>
		      			@endforeach
		      		</tbody>
		      	</table>
		    </div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->
@endsection

@section('script')
	<!-- DATA TABLES SCRIPT -->
	<script src="{{ asset("admin_theme/plugins/datatables/jquery.dataTables.js") }}" type="text/javascript"></script>
	<script src="{{ asset("admin_theme/plugins/datatables/dataTables.bootstrap.js") }}" type="text/javascript"></script>

	<script type="text/javascript">
		$(function () {
			var table = $('#data_table').DataTable({
				"paging": false,
				"lengthChange": false,
				"searching": true,
				"ordering": true,
				"info": false,
				"autoWidth": true,
				"scrollX": true
			});
		});		
	</script>
@endsection