app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => ['web']], function () {

    Route::get('/', function () {
        return redirect()->action('RankingController@overall');
    });

    // Auth
    Route::group(['namespace' => 'Auth'], function(){
        Route::get('login', [
            'as'   => 'auth.login',
            'uses' =>  'AuthController@getLogin'
        ]);
        
        Route::post('login',[
            'as'   => 'auth.login',
            'uses' =>  'AuthController@postLogin'
        ]);

        Route::get('logout', [
            'as'   => 'auth.logout',
            'uses' =>  'AuthController@logout'
        ]);
    });

    // Ranking
    Route::get('ranking/overall', [
        'as' => 'ranking.overall',
        'uses' => 'RankingController@overall'
    ]);
    Route::get('ranking/overall/vice-president', [
        'as' => 'ranking.overall-vice-president',
        'uses' => 'RankingController@overallVicePresident'
    ]);
    Route::get('ranking/regional', [
        'as' => 'ranking.regional',
        'uses' => 'RankingController@regional'
    ]);
    Route::get('ranking/regional/vice-president', [
        'as' => 'ranking.regional-vice-president',
        'uses' => 'RankingController@regionalVicePresident'
    ]);
    Route::get('ranking/provincial', [
        'as' => 'ranking.provincial',
        'uses' => 'RankingController@provincial'
    ]);
    Route::get('ranking/provincial/vice-president', [
        'as' => 'ranking.provincial-vice-president',
        'uses' => 'RankingController@provincialVicePresident'
    ]);
    Route::get('ranking/coc/president', [
        'as' => 'ranking.coc-president',
        'uses' => 'RankingController@cocPresident'
    ]);
    Route::get('ranking/coc/vice-president', [
        'as' => 'ranking.coc-vice-president',
        'uses' => 'RankingController@cocVicePresident'
    ]);

    // Maps
    Route::get('ranking/map/count-received-president', [
        'as' => 'ranking.count-received-president',
        'uses' => 'RankingController@countReceivedPresident'
    ]);
    Route::get('ranking/map/count-received-vice-president', [
        'as' => 'ranking.count-received-vice-president',
        'uses' => 'RankingController@countReceivedVicePresident'
    ]);
    Route::get('ranking/map/per-area-president', [
        'as' => 'ranking.per-area-president',
        'uses' => 'RankingController@perAreaPresident'
    ]);
    Route::get('ranking/map/per-area-vice-president', [
        'as' => 'ranking.per-area-vice-president',
        'uses' => 'RankingController@perAreaVicePresident'
    ]);
    

    // Reports
    Route::get('report/voters-turnout/regional', [
        'as' => 'report.voters-turnout-regional',
        'uses' => 'ReportController@votersTurnoutRegional'
    ]);
    Route::get('report/voters-turnout/provincial', [
        'as' => 'report.voters-turnout-provincial',
        'uses' => 'ReportController@votersTurnoutProvincial'
    ]);
    Route::get('report/discrepancies-president', [
        'as' => 'report.discrepancies-president',
        'uses' => 'ReportController@discrepanciesPresident'
    ]);
    Route::get('report/discrepancies-vice-president', [
        'as' => 'report.discrepancies-vice-president',
        'uses' => 'ReportController@discrepanciesVicePresident'
    ]);
    Route::get('report/registered-vs-actual-president', [
        'as' => 'report.registered-vs-actual-president',
        'uses' => 'ReportController@registeredVsActualPresident'
    ]);
    Route::get('report/registered-vs-actual-vice-president', [
        'as' => 'report.registered-vs-actual-vice-president',
        'uses' => 'ReportController@registeredVsActualVicePresident'
    ]);
    Route::get('report/registered-vs-coc-president', [
        'as' => 'report.registered-vs-coc-president',
        'uses' => 'ReportController@registeredVsCocPresident'
    ]);
    Route::get('report/registered-vs-coc-vice-president', [
        'as' => 'report.registered-vs-coc-vice-president',
        'uses' => 'ReportController@registeredVsCocVicePresident'
    ]);

    // Input
    // Admin
    Route::group(['prefix' => 'input'], function(){
        Route::get('import', [
            'as' => 'import',
            'uses' => 'ImportController@import'
        ]);

        // Manual Quick Count
        Route::get('manual', [
            'as' => 'manual',
            'uses' => 'OfficialCountController@presidentIndex'
        ]);
        Route::get('manual/{candidate_id}/{province_id}/edit', [
            'as' => 'manual.edit',
            'uses' => 'OfficialCountController@editCount'
        ]);
        Route::post('manual/{candidate_id}/{province_id}/update', [
            'as' => 'manual.update',
            'uses' => 'OfficialCountController@updateCount'
        ]);
        Route::get('manual/vice-president', [
            'as' => 'manual.vice-president',
            'uses' => 'OfficialCountController@vicePresidentIndex'
        ]);
        Route::get('manual/vice-president/{candidate_id}/{province_id}/edit', [
            'as' => 'manual.vice-president.edit',
            'uses' => 'OfficialCountController@editVicePresidentCount'
        ]);
        Route::post('manual/vice-president/{candidate_id}/{province_id}/update', [
            'as' => 'manual.vice-president.update',
            'uses' => 'OfficialCountController@updateVicePresidentCount'
        ]);
        // Monitoring
        Route::get('monitoring', [
            'as' => 'manual.monitoring',
            'uses' => 'MonitoringController@index'
        ]);
        Route::get('monitoring/{province_id}/edit', [
            'as' => 'manual.monitoring.edit',
            'uses' => 'MonitoringController@edit'
        ]);
        Route::post('monitoring/{province_id}/update', [
            'as' => 'manual.monitoring.update',
            'uses' => 'MonitoringController@update'
        ]);

        // PPCRV COC
        Route::get('ppcrv-coc', [
            'as' => 'ppcrv-coc',
            'uses' => 'PpcrvCountController@index'
        ]);
        Route::get('ppcrv-coc/{province_id}/edit', [
            'as' => 'ppcrv-coc.edit',
            'uses' => 'PpcrvCountController@edit'
        ]);
        Route::post('ppcrv-coc/{province_id}/update', [
            'as' => 'ppcrv-coc.update',
            'uses' => 'PpcrvCountController@update'
        ]);
    });

    // Admin
    Route::group(['prefix' => 'admin'], function(){
        Route::resource('candidate', 'CandidateController');
        // User
        Route::get('user/{id}/change-password', [
            'as' => 'admin.user.change-password',
            'uses' =>  'UserController@changePassword'
        ]);
        Route::post('user/{id}/updatePassword', [
            'as' => 'admin.user.update-password',
            'uses' => 'UserController@updatePassword'
        ]);
        Route::resource('user', 'UserController');

        // Configuration
        Route::get('config/reset-database', [
            'as' => 'config.reset-database',
            'uses' => 'ConfigController@resetDatabase'
        ]);
        Route::post('config/save-reset-database', [
            'as' => 'config.save-reset-database',
            'uses' => 'ConfigController@saveResetDatabase'
        ]);
    });
    

});

app/Candidate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use DB;

class Candidate extends Model
{
    use SoftDeletes;

    protected $fillable = ['first_name', 'last_name', 'middle_name', 'display_name',
    	'code', 'position', 'photo', 'remarks', 'color', 'last_updated_by'];

    protected $dates = ['deleted_at'];

    public function getOverallQuickCount()
    {
        $count = 0;
        $provinces = Province::all();

        foreach($provinces as $province) {
            $quickCount = OfficialCount::where('candidate_id', $this->id)
                ->where('province_id', $province->id)
                ->orderBy('id', 'desc')
                ->first();

            if($quickCount) $count += $quickCount;
        }
       
        return $count;
    }

    public function getNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;

class User extends Authenticatable implements AuthorizableContract
{
    use Authorizable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\User;
use Gate;

class UserController extends Controller
{
    function __construct()
    {
        ini_set('xdebug.max_nesting_level', 200);

        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        if(Gate::denies('manage-users')) {
            return redirect('/');
        }

        $users = User::all();

        return view('user.index')
            ->with('users', $users)
            ->with('page_title', 'List of Users');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Gate::denies('manage-users')) {
            return redirect('/');
        }

        $roles = $this->getRoles();

        return view('user.create')
            ->with('user', null)
            ->with('roles', $roles)
            ->with('page_title', 'Create User');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(Gate::denies('manage-users')) {
            return redirect('/');
        }

        $this->validate($request, [
            'name' => 'required',
            'role' => 'required',
            'email' => 'required|unique:users|max:150',
            'password' => 'required|confirmed',
        ]);

        $user = new User;
        $user->name = $request->name;
        $user->role = $request->role;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->save();

        $request->session()->flash('success_message', 'Successfully added user, <strong>'.$request->name.'</strong>.');

        return redirect()->route('admin.user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Gate::denies('manage-users')) {
            return redirect('/');
        }

        $user = User::find($id);
        $roles = $this->getRoles();

        return view('user.edit')
            ->with('user', $user)
            ->with('roles', $roles)
            ->with('page_title', 'Edit User');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Gate::denies('manage-users')) {
            return redirect('/');
        }
        
        $this->validate($request, [
            'name' => 'required',
            'role' => 'required',
        ]);
        
        $user = User::find($id);
        $user->name = $request->name;
        $user->role = $request->role;
        $user->email = $request->email;
        $user->save();

        $request->session()->flash('success_message', 'Successfully updated user, <strong>'.$request->name.'</strong>.');

        return redirect()->route('admin.user.edit', $id);
    }

    public function changePassword($id)
    {
        if(Gate::denies('manage-users')) {
            return redirect('/');
        }

        $user = User::find($id);

        return view('user/change_password')
            ->with('user', $user)
            ->with('page_title', 'Change Password');
    }

    public function updatePassword(Request $request, $id)
    {
        if(Gate::denies('manage-users')) {
            return redirect('/');
        }
        
        $this->validate($request, [
            'password' => 'required|confirmed'
        ]);

        $user = User::find($id);
        $user->password = bcrypt($request->password);
        $user->save();

        $request->session()->flash('success_message', 'Successfully updated password of user, <strong>'.$user->name.'</strong>.');

        return redirect()->route('admin.user.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if(Gate::denies('manage-users')) {
            return redirect('/');
        }

        $user = User::find($id);
        $user->delete();
        
        $request->session()->flash('success_message', 'Successfully deleted user, <strong>'.$user->name.'</strong>.');
        
        return redirect()->route('admin.user.index');
    }

    private function getRoles()
    {
        return array('admin' => 'Admin',
            'encoder' => 'Encoder',
            'checker' => 'Checker');
    }
}

resources/views/user/change_password.blade.php
@extends('admin_template')

@section('content')
	<form action="{{ route('admin.user.update-password', $user->id) }}" method="POST" enctype="multipart/form-data">
		{!! csrf_field() !!}

	    <div class="row">
		    <div class="col-xs-12">
		      <div class="box">
		        <div class="box-body">
		        	<h4>{{ $user->name }}</h4>

	                <div class="form-group  {{ $errors->has('password') ? 'has-error' : '' }}">
	                  <label>New Password</label>
	                  <input type="password" name="password" class="form-control" />
	                </div>

	                <div class="form-group  {{ $errors->has('password') ? 'has-error' : '' }}">
	                  <label>Confirm Password</label>
	                  <input type="password" name="password_confirmation" class="form-control" />
	                </div>
		        </div><!-- /.box-body -->
		      </div><!-- /.box -->
		    </div><!-- /.col -->
		</div><!-- /.row -->

		<div class="row">
			<div class="col-xs-12">
				<button type="submit" class="btn btn-primary btn-flat">Change User Password</button>
				<a href="{{ route('admin.user.edit', $user->id) }}" class="btn"><u>Cancel</u></a>
			</div>
		</div>

	</form>	  
@endsection

resources/views/user/create.blade.php
@extends('admin_template')

@section('head')
	
@endsection

@section('content')
	{!! Form::model($user, ['method' => 'POST', 'route' => ['admin.user.store'], 'files' => true]) !!}
	    @include('user.form', ['mode' => 'create'])
		<div class="row">
		    <div class="col-xs-12">
		    	<div class="pull-left">
	    			<button type="submit" class="btn btn-primary btn-flat">Create User</button>
		            <a href="{{ route('admin.user.index') }}" class="btn"><u>Cancel</u></a>
		    	</div>
		    </div>
		</div>
	{!! Form::close() !!}	    
@endsection

@section('script')
	
@endsection

resources/views/user/edit.blade.php
@extends('admin_template')

@section('content')
	{!! Form::model($user, ['method' => 'PUT', 'route' => ['admin.user.update', $user->id], 'files' => true]) !!}
	    @include('user.form', ['mode' => 'edit'])
	    {!! Form::submit('', ['id' => 'submit-form', 'class' => 'hidden']) !!}
	{!! Form::close() !!}
		<div class="row">
		    <div class="col-xs-12">
		    	<div class="pull-left">
		    		<label for="submit-form" class="btn btn-primary btn-flat">Update User</label>
		            <a href="{{ route('admin.user.index') }}" class="btn"><u>Cancel</u></a>
		    	</div>
		    	<div class="pull-right">
		    		{!! Form::open(['method' => 'DELETE', 'route' => ['admin.user.destroy', $user->id]]) !!}
						@if(is_null($user->deleted_at))
							<button type="submit" class="btn btn-danger btn-sm btn-flat" onclick="return confirm('Are you sure you want to delete user?')"><strong>Delete User</strong></button>
						@endif
						<a href="{{ route('admin.user.change-password', $user->id) }}" class="btn btn-default btn-sm btn-flat"><strong>Change Password</strong></a>
					{!! Form::close() !!}
		    	</div>
		    </div>
		</div>
	{!! Form::close() !!}
@endsection

resources/views/user/form.blade.php
<div class="row">
  <div class="col-xs-12">
    <div class="box">
    	<div class="box-header with-border">
        <!-- <h3 class="box-title">Enroller Profile</h3> -->
      </div><!-- /.box-header -->
      <div class="box-body">
        <div class="form-group  {{ $errors->has('name') ? 'has-error' : '' }}">
          <label>Name</label>
          {!! Form::text('name', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group  {{ $errors->has('role') ? 'has-error' : '' }}">
          <label>Role</label>
          {!! Form::select('role', $roles, null, ['placeholder' => '- Select Role -', 'class' => 'form-control', 'style' => 'width:100%']) !!}
        </div>
        <div class="form-group  {{ $errors->has('email') ? 'has-error' : '' }}">
          <label>Username</label>
          {!! Form::text('email', null, ['class' => 'form-control']) !!}
        </div>

        @if($mode === 'create')
          <div class="form-group  {{ $errors->has('password') ? 'has-error' : '' }}">
            <label>Password</label>
            {!! Form::password('password', ['class' => 'form-control']) !!}
          </div>

          <div class="form-group  {{ $errors->has('password') ? 'has-error' : '' }}">
            <label>Confirm Password</label>
            {!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
          </div>
        @endif
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div><!-- /.col -->
</div><!-- /.row -->

resources/views/user/index.blade.php
@extends('admin_template')

@section('head')
	<!-- DATA TABLES -->
    <link href="{{ asset('admin_theme/plugins/datatables/dataTables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')
<div class="row">
	<div class="col-xs-12">
		<a href="{{ route('admin.user.create') }}" class="btn btn-primary btn-flat fa fa-plus"> Add New</a>
		<br/><br/>

		<div class="box">
	      	<div class="box-header">
	      		<!-- <h3 class="box-title">President</h3> -->
	      	</div><!-- /.box-header -->
	      	<div class="box-body">
		      	<table id="data_table" class="table table-bordered table-striped">
		      		<thead>
		      			<tr>
		      				<th>Name</th>
		      				<th>Role</th>
		      				<th></th>
		      			</tr>
		      		</thead>
		      		<tbody>
		      		@foreach($users as $user)
		      			<tr>
		      				<td>{{ $user->name }}</td>
		      				<td>{{ $user->role }}</td>
		      				<td align="center"><a href="{{ route('admin.user.edit', $user->id) }}"><i class="fa fa-pencil"></i></a></td>
		      			</tr>
		      		@endforeach
		      		</tbody>
		      	</table>
		    </div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->
@endsection

@section('script')
	<!-- DATA TABLES SCRIPT -->
	<script src="{{ asset("admin_theme/plugins/datatables/jquery.dataTables.js") }}" type="text/javascript"></script>
	<script src="{{ asset("admin_theme/plugins/datatables/dataTables.bootstrap.js") }}" type="text/javascript"></script>

	<script type="text/javascript">
		$(function () {
			var table = $('#data_table').DataTable({
				"paging": false,
				"lengthChange": false,
				"searching": true,
				"ordering": true,
				"info": false,
				"autoWidth": true,
				"scrollX": true
			});
		});		
	</script>
@endsection