app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => ['web']], function () {

    Route::get('/', function () {
        return redirect()->action('RankingController@overall');
    });

    // Auth
    Route::group(['namespace' => 'Auth'], function(){
        Route::get('login', [
            'as'   => 'auth.login',
            'uses' =>  'AuthController@getLogin'
        ]);
        
        Route::post('login',[
            'as'   => 'auth.login',
            'uses' =>  'AuthController@postLogin'
        ]);

        Route::get('logout', [
            'as'   => 'auth.logout',
            'uses' =>  'AuthController@logout'
        ]);
    });

    // Ranking
    Route::get('ranking/overall', [
        'as' => 'ranking.overall',
        'uses' => 'RankingController@overall'
    ]);
    Route::get('ranking/overall/vice-president', [
        'as' => 'ranking.overall-vice-president',
        'uses' => 'RankingController@overallVicePresident'
    ]);
    Route::get('ranking/regional', [
        'as' => 'ranking.regional',
        'uses' => 'RankingController@regional'
    ]);
    Route::get('ranking/regional/vice-president', [
        'as' => 'ranking.regional-vice-president',
        'uses' => 'RankingController@regionalVicePresident'
    ]);
    Route::get('ranking/provincial', [
        'as' => 'ranking.provincial',
        'uses' => 'RankingController@provincial'
    ]);
    Route::get('ranking/provincial/vice-president', [
        'as' => 'ranking.provincial-vice-president',
        'uses' => 'RankingController@provincialVicePresident'
    ]);
    Route::get('ranking/coc/president', [
        'as' => 'ranking.coc-president',
        'uses' => 'RankingController@cocPresident'
    ]);
    Route::get('ranking/coc/vice-president', [
        'as' => 'ranking.coc-vice-president',
        'uses' => 'RankingController@cocVicePresident'
    ]);

    // Maps
    Route::get('ranking/map/count-received-president', [
        'as' => 'ranking.count-received-president',
        'uses' => 'RankingController@countReceivedPresident'
    ]);
    Route::get('ranking/map/count-received-vice-president', [
        'as' => 'ranking.count-received-vice-president',
        'uses' => 'RankingController@countReceivedVicePresident'
    ]);
    Route::get('ranking/map/per-area-president', [
        'as' => 'ranking.per-area-president',
        'uses' => 'RankingController@perAreaPresident'
    ]);
    Route::get('ranking/map/per-area-vice-president', [
        'as' => 'ranking.per-area-vice-president',
        'uses' => 'RankingController@perAreaVicePresident'
    ]);
    

    // Reports
    Route::get('report/voters-turnout/regional', [
        'as' => 'report.voters-turnout-regional',
        'uses' => 'ReportController@votersTurnoutRegional'
    ]);
    Route::get('report/voters-turnout/provincial', [
        'as' => 'report.voters-turnout-provincial',
        'uses' => 'ReportController@votersTurnoutProvincial'
    ]);
    Route::get('report/discrepancies-president', [
        'as' => 'report.discrepancies-president',
        'uses' => 'ReportController@discrepanciesPresident'
    ]);
    Route::get('report/discrepancies-vice-president', [
        'as' => 'report.discrepancies-vice-president',
        'uses' => 'ReportController@discrepanciesVicePresident'
    ]);
    Route::get('report/registered-vs-actual-president', [
        'as' => 'report.registered-vs-actual-president',
        'uses' => 'ReportController@registeredVsActualPresident'
    ]);
    Route::get('report/registered-vs-actual-vice-president', [
        'as' => 'report.registered-vs-actual-vice-president',
        'uses' => 'ReportController@registeredVsActualVicePresident'
    ]);
    Route::get('report/registered-vs-coc-president', [
        'as' => 'report.registered-vs-coc-president',
        'uses' => 'ReportController@registeredVsCocPresident'
    ]);
    Route::get('report/registered-vs-coc-vice-president', [
        'as' => 'report.registered-vs-coc-vice-president',
        'uses' => 'ReportController@registeredVsCocVicePresident'
    ]);

    // Input
    // Admin
    Route::group(['prefix' => 'input'], function(){
        Route::get('import', [
            'as' => 'import',
            'uses' => 'ImportController@import'
        ]);

        // Manual Quick Count
        Route::get('manual', [
            'as' => 'manual',
            'uses' => 'OfficialCountController@presidentIndex'
        ]);
        Route::get('manual/{candidate_id}/{province_id}/edit', [
            'as' => 'manual.edit',
            'uses' => 'OfficialCountController@editCount'
        ]);
        Route::post('manual/{candidate_id}/{province_id}/update', [
            'as' => 'manual.update',
            'uses' => 'OfficialCountController@updateCount'
        ]);
        Route::get('manual/vice-president', [
            'as' => 'manual.vice-president',
            'uses' => 'OfficialCountController@vicePresidentIndex'
        ]);
        Route::get('manual/vice-president/{candidate_id}/{province_id}/edit', [
            'as' => 'manual.vice-president.edit',
            'uses' => 'OfficialCountController@editVicePresidentCount'
        ]);
        Route::post('manual/vice-president/{candidate_id}/{province_id}/update', [
            'as' => 'manual.vice-president.update',
            'uses' => 'OfficialCountController@updateVicePresidentCount'
        ]);
        // Monitoring
        Route::get('monitoring', [
            'as' => 'manual.monitoring',
            'uses' => 'MonitoringController@index'
        ]);
        Route::get('monitoring/{province_id}/edit', [
            'as' => 'manual.monitoring.edit',
            'uses' => 'MonitoringController@edit'
        ]);
        Route::post('monitoring/{province_id}/update', [
            'as' => 'manual.monitoring.update',
            'uses' => 'MonitoringController@update'
        ]);

        // PPCRV COC
        Route::get('ppcrv-coc', [
            'as' => 'ppcrv-coc',
            'uses' => 'PpcrvCountController@index'
        ]);
        Route::get('ppcrv-coc/{province_id}/edit', [
            'as' => 'ppcrv-coc.edit',
            'uses' => 'PpcrvCountController@edit'
        ]);
        Route::post('ppcrv-coc/{province_id}/update', [
            'as' => 'ppcrv-coc.update',
            'uses' => 'PpcrvCountController@update'
        ]);
    });

    // Admin
    Route::group(['prefix' => 'admin'], function(){
        Route::resource('candidate', 'CandidateController');
        // User
        Route::get('user/{id}/change-password', [
            'as' => 'admin.user.change-password',
            'uses' =>  'UserController@changePassword'
        ]);
        Route::post('user/{id}/updatePassword', [
            'as' => 'admin.user.update-password',
            'uses' => 'UserController@updatePassword'
        ]);
        Route::resource('user', 'UserController');

        // Configuration
        Route::get('config/reset-database', [
            'as' => 'config.reset-database',
            'uses' => 'ConfigController@resetDatabase'
        ]);
        Route::post('config/save-reset-database', [
            'as' => 'config.save-reset-database',
            'uses' => 'ConfigController@saveResetDatabase'
        ]);
    });
    

});

app/Candidate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use DB;

class Candidate extends Model
{
    use SoftDeletes;

    protected $fillable = ['first_name', 'last_name', 'middle_name', 'display_name',
    	'code', 'position', 'photo', 'remarks', 'color', 'last_updated_by'];

    protected $dates = ['deleted_at'];

    public function getOverallQuickCount()
    {
        $count = 0;
        $provinces = Province::all();

        foreach($provinces as $province) {
            $quickCount = OfficialCount::where('candidate_id', $this->id)
                ->where('province_id', $province->id)
                ->orderBy('id', 'desc')
                ->first();

            if($quickCount) $count += $quickCount;
        }
       
        return $count;
    }

    public function getNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }
}

resources/views/input/manual/monitoring_edit.blade.php
@extends('admin_template')

@section('content')
	{!! Form::model($monitoring, ['method' => 'POST', 'route' => ['manual.monitoring.update', $province->id]]) !!}
	    <div class="row">
		  <div class="col-xs-12">
		    <div class="box">
		    	<div class="box-header with-border">
		        <!-- <h3 class="box-title">Enroller Profile</h3> -->
		      </div><!-- /.box-header -->
		      <div class="box-body">
		        <div class="form-group  {{ $errors->has('province') ? 'has-error' : '' }}">
		          <label>Province</label>
		          {{ $province->name }} ({{ $province->code }})
		        </div>
		        <div class="form-group  {{ $errors->has('monitoring') ? 'has-error' : '' }}">
		          <label>Monitoring</label><br>
		          {!! Form::checkbox('text', '1') !!} Text <br>
		          {!! Form::checkbox('viber', '1') !!} Viber <br>
		          {!! Form::checkbox('call', '1') !!} Call <br>
		        </div>
		      </div><!-- /.box-body -->
		    </div><!-- /.box -->
		  </div><!-- /.col -->
		</div><!-- /.row -->
	    {!! Form::submit('', ['id' => 'submit-form', 'class' => 'hidden']) !!}
	{!! Form::close() !!}
		<div class="row">
		    <div class="col-xs-12">
		    	<div class="pull-left">
		    		<label for="submit-form" class="btn btn-primary btn-flat">Update</label>
		            <a href="{{ route('manual.monitoring') }}" class="btn"><u>Cancel</u></a>
		    	</div>
		    </div>
		</div>
@endsection

@section('script')
@endsection

resources/views/input/manual/monitoring_index.blade.php
@extends('admin_template')

@section('head')
	<!-- DATA TABLES -->
    <link href="{{ asset('admin_theme/plugins/datatables/dataTables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')
<div class="row">
	<div class="col-xs-12 text-center">
	@can('manual-input')
		<a href="{{ route('manual') }}" class="btn btn-default btn-flat btn-sm">President</a>
		<a href="{{ route('manual.vice-president') }}" class="btn btn-default btn-flat btn-sm">Vice President</a>
	@endcan
	@can('monitoring')
		<a href="{{ route('manual.monitoring') }}" class="btn btn-primary btn-flat btn-sm">Monitoring</a>
	@endcan
		<br><br>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
	      	<div class="box-header">
	      		<!-- <h3 class="box-title">President</h3> -->
	      	</div><!-- /.box-header -->
	      	<div class="box-body">
		      	<table id="data_table" class="table table-bordered table-striped">
		      		<thead>
		      			<tr>
		      				<th>Province</th>
		      				<th>Region</th>
		      				<th>Text</th>
		      				<th>Viber</th>
		      				<th>Call</th>
		      				<th></th>
		      			</tr>
		      		</thead>
		      		<tbody>
		      		@foreach($provinces as $province)
		      			<tr>
		      				<td>{{ $province->name }}  ({{ $province->code }})</td>
		      				<td>{{ $province->region->name }}</td>
		      				<td align="center">
			      				@if($province->monitoring && $province->monitoring->text)
			      					&#10003;
			      				@endif
		      				</td>
		      				<td align="center">
		      					@if($province->monitoring && $province->monitoring->viber)
			      					&#10003;
			      				@endif
		      				</td>
		      				<td align="center">
		      					@if($province->monitoring && $province->monitoring->call)
			      					&#10003;
			      				@endif
		      				</td>
		      				<td align="center"><a href="{{ route('manual.monitoring.edit', $province->id) }}"><i class="fa fa-pencil"></i></a></td>
		      			</tr>
		      		@endforeach
		      		</tbody>
		      	</table>
		    </div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->
@endsection

@section('script')
	<!-- DATA TABLES SCRIPT -->
	<script src="{{ asset("admin_theme/plugins/datatables/jquery.dataTables.js") }}" type="text/javascript"></script>
	<script src="{{ asset("admin_theme/plugins/datatables/dataTables.bootstrap.js") }}" type="text/javascript"></script>

	<script type="text/javascript">
		$(function () {
			var table = $('#data_table').DataTable({
				"paging": false,
				"lengthChange": false,
				"searching": true,
				"ordering": true,
				"info": false,
				"autoWidth": true,
				"scrollX": true
			});
		});		
	</script>
@endsection

resources/views/input/manual/president_edit.blade.php
@extends('admin_template')

@section('head')
@endsection

@section('breadcrumbs')
@endsection

@section('content')
	{!! Form::model($officialCount, ['method' => 'POST', 'route' => ['manual.update', $candidate->id, $province->id], 'files' => true]) !!}
	    <div class="row">
		  <div class="col-xs-12">
		    <div class="box">
		    	<div class="box-header with-border">
		        <!-- <h3 class="box-title">Enroller Profile</h3> -->
		      </div><!-- /.box-header -->
		      <div class="box-body">
		      	<div class="form-group  {{ $errors->has('candidate') ? 'has-error' : '' }}">
		          <label>Candidate</label>
		          {{ $candidate->first_name . ' ' . $candidate->last_name }}
		        </div>
		        <div class="form-group  {{ $errors->has('province') ? 'has-error' : '' }}">
		          <label>Province</label>
		          {{ $province->name }}
		        </div>
		        <div class="form-group  {{ $errors->has('count') ? 'has-error' : '' }}">
		          <label>Count</label>
		          {!! Form::text('count', null, ['class' => 'form-control']) !!}
		        </div>
		      </div><!-- /.box-body -->
		    </div><!-- /.box -->
		  </div><!-- /.col -->
		</div><!-- /.row -->
	    {!! Form::submit('', ['id' => 'submit-form', 'class' => 'hidden']) !!}
	{!! Form::close() !!}
		<div class="row">
		    <div class="col-xs-12">
		    	<div class="pull-left">
		    		<label for="submit-form" class="btn btn-primary btn-flat">Update Count</label>
		            <a href="{{ route('manual') }}" class="btn"><u>Cancel</u></a>
		    	</div>
		    </div>
		</div>
	{!! Form::close() !!}
@endsection

@section('script')
@endsection

resources/views/input/manual/president_index.blade.php
@extends('admin_template')

@section('head')
	<!-- DATA TABLES -->
    <link href="{{ asset('admin_theme/plugins/datatables/dataTables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')
<div class="row">
	<div class="col-xs-12 text-center">
	@can('manual-input')
		<a href="{{ route('manual') }}" class="btn btn-primary btn-flat btn-sm">President</a>
		<a href="{{ route('manual.vice-president') }}" class="btn btn-default btn-flat btn-sm">Vice President</a>
	@endcan
	@can('monitoring')
		<a href="{{ route('manual.monitoring') }}" class="btn btn-default btn-flat btn-sm">Monitoring</a>
	@endcan
		<br><br>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
	      	<div class="box-header">
	      		<!-- <h3 class="box-title">President</h3> -->
	      	</div><!-- /.box-header -->
	      	<div class="box-body">
		      	<table id="data_table" class="table table-bordered table-striped">
		      		<thead>
		      			<tr>
		      				<th>Province</th>
		      				<th>Region</th>
		      				@foreach($candidates as $candidate)
		      					<th>{{ $candidate->last_name }}</th>
		      				@endforeach
		      			</tr>
		      		</thead>
		      		<tbody>
		      		@foreach($provinces as $province)
		      			<tr>
		      				<td>{{ $province->name }} ({{ $province->zip_code }})</td>
		      				<td>{{ $province->region->name }}</td>
		      				@foreach($candidates as $candidate)
		      					<td align="right">{{ number_format($province->getCandidateQuickCount($candidate->id, $province->id)) }}<a href="{{ route('manual.edit', [$candidate->id, $province->id]) }}">&nbsp;&nbsp;&nbsp;<i class="fa fa-pencil"></i></a></td>
		      				@endforeach
		      			</tr>
		      		@endforeach
		      		</tbody>
		      	</table>
		    </div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->
@endsection

@section('script')
	<!-- DATA TABLES SCRIPT -->
	<script src="{{ asset("admin_theme/plugins/datatables/jquery.dataTables.js") }}" type="text/javascript"></script>
	<script src="{{ asset("admin_theme/plugins/datatables/dataTables.bootstrap.js") }}" type="text/javascript"></script>

	<script type="text/javascript">
		$(function () {
			var table = $('#data_table').DataTable({
				"paging": false,
				"lengthChange": false,
				"searching": true,
				"ordering": true,
				"info": false,
				"autoWidth": true,
				"scrollX": true
			});
		});		
	</script>
@endsection

resources/views/input/manual/vice_president_edit.blade.php
@extends('admin_template')

@section('head')
@endsection

@section('breadcrumbs')
@endsection

@section('content')
	{!! Form::model($officialCount, ['method' => 'POST', 'route' => ['manual.vice-president.update', $candidate->id, $province->id], 'files' => true]) !!}
	    <div class="row">
		  <div class="col-xs-12">
		    <div class="box">
		    	<div class="box-header with-border">
		        <!-- <h3 class="box-title">Enroller Profile</h3> -->
		      </div><!-- /.box-header -->
		      <div class="box-body">
		      	<div class="form-group  {{ $errors->has('candidate') ? 'has-error' : '' }}">
		          <label>Candidate</label>
		          {{ $candidate->first_name . ' ' . $candidate->last_name }}
		        </div>
		        <div class="form-group  {{ $errors->has('province') ? 'has-error' : '' }}">
		          <label>Province</label>
		          {{ $province->name }}
		        </div>
		        <div class="form-group  {{ $errors->has('count') ? 'has-error' : '' }}">
		          <label>Count</label>
		          {!! Form::text('count', null, ['class' => 'form-control']) !!}
		        </div>
		      </div><!-- /.box-body -->
		    </div><!-- /.box -->
		  </div><!-- /.col -->
		</div><!-- /.row -->
	    {!! Form::submit('', ['id' => 'submit-form', 'class' => 'hidden']) !!}
	{!! Form::close() !!}
		<div class="row">
		    <div class="col-xs-12">
		    	<div class="pull-left">
		    		<label for="submit-form" class="btn btn-primary btn-flat">Update Count</label>
		            <a href="{{ route('manual.vice-president') }}" class="btn"><u>Cancel</u></a>
		    	</div>
		    </div>
		</div>
	{!! Form::close() !!}
@endsection

@section('script')
@endsection

resources/views/input/manual/vice_president_index.blade.php
@extends('admin_template')

@section('head')
	<!-- DATA TABLES -->
    <link href="{{ asset('admin_theme/plugins/datatables/dataTables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')
<div class="row">
	<div class="col-xs-12 text-center">
	@can('manual-input')
		<a href="{{ route('manual') }}" class="btn btn-default btn-flat btn-sm">President</a>
		<a href="{{ route('manual.vice-president') }}" class="btn btn-primary btn-flat btn-sm">Vice President</a>
	@endcan
	@can('monitoring')
		<a href="{{ route('manual.monitoring') }}" class="btn btn-default btn-flat btn-sm">Monitoring</a>
	@endcan
		<br><br>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
	      	<div class="box-header">
	      		<!-- <h3 class="box-title">President</h3> -->
	      	</div><!-- /.box-header -->
	      	<div class="box-body">
		      	<table id="data_table" class="table table-bordered table-striped">
		      		<thead>
		      			<tr>
		      				<th>Province</th>
		      				<th>Region</th>
		      				@foreach($candidates as $candidate)
		      					<th>{{ $candidate->last_name }}</th>
		      				@endforeach
		      			</tr>
		      		</thead>
		      		<tbody>
		      		@foreach($provinces as $province)
		      			<tr>
		      				<td>{{ $province->name }} ({{ $province->zip_code }})</td>
		      				<td>{{ $province->region->name }}</td>
		      				@foreach($candidates as $candidate)
		      					<td align="right">{{ number_format($province->getCandidateQuickCount($candidate->id, $province->id)) }}<a href="{{ route('manual.vice-president.edit', [$candidate->id, $province->id]) }}">&nbsp;&nbsp;&nbsp;<i class="fa fa-pencil"></i></a></td>
		      				@endforeach
		      			</tr>
		      		@endforeach
		      		</tbody>
		      	</table>
		    </div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->
@endsection

@section('script')
	<!-- DATA TABLES SCRIPT -->
	<script src="{{ asset("admin_theme/plugins/datatables/jquery.dataTables.js") }}" type="text/javascript"></script>
	<script src="{{ asset("admin_theme/plugins/datatables/dataTables.bootstrap.js") }}" type="text/javascript"></script>

	<script type="text/javascript">
		$(function () {
			var table = $('#data_table').DataTable({
				"paging": false,
				"lengthChange": false,
				"searching": true,
				"ordering": true,
				"info": false,
				"autoWidth": true,
				"scrollX": true
			});
		});		
	</script>
@endsection